version: "3"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: gorm
      POSTGRES_PASSWORD: gorm
      POSTGRES_DB: gorm
    ports:
      - 5432:5432
  app:
    container_name: go-api
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
      # - app-volume:/app
    tty: true
    depends_on:
      - db
    ports:
      - 8080:8080
    env_file: .env

# volumes:
#   app-volume:
#     driver: azure_file
#     driver_opts:
#       share_name: app-volume
#       storage_account_name: smaruteamb
